# Generated by Django 2.0 on 2017-12-24 14:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_content_summary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='source',
            name='last_sync',
            field=models.DateTimeField(default=datetime.datetime(2017, 12, 24, 14, 20, 26, 460776)),
        ),
    ]
