# Generated by Django 2.0 on 2017-12-24 14:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_auto_20171224_1420'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='summary',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='source',
            name='last_sync',
            field=models.DateTimeField(default=datetime.datetime(2017, 12, 24, 14, 58, 37, 100690)),
        ),
    ]
